### PR TITLE
Modified

### PR DESCRIPTION
**Pull request by HAKSOAT**

### CODE REVIEW

**Review by tiemma — APPROVED** [review]

**Review by tiemma — COMMENTED** [review]
Great adding in the guide in the curriculum.

Let's add it to the README.md also

Kindly check here for an example:
https://github.com/ashinzekene/react-music-player

**Comment by HAKSOAT** [comment]
Okay. I'll do that.

**Comment by HAKSOAT** [comment]
The guide was added to  the README though

**Review by tiemma — COMMENTED** [review]
Oh, I see it now

My error

**Comment by tiemma** [comment]
Great work man!!!!!

**Pull request merged**
